---
# Install Elasticsearch packages on debian based distributions.

- name: Add Elasticsearch apt key
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present

- name: Install apt-transport-https dependency.
  apt: name=apt-transport-https update_cache=yes state=latest install_recommends=no

- name: Install Elasticsearch repo
  apt_repository: repo="deb https://artifacts.elastic.co/packages/5.x/apt stable main" state=present

- name: Install Elasticsearch package
  apt: name=elasticsearch update_cache=yes state=latest install_recommends=no

- name: Configure Elasticsearch.
  include: elasticsearch.yml
